#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "deco-create"
main = "server/main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "kmute"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[deco]
workspace = "kmute"
enable_workflows = true
local = false

[[deco.bindings]]
name = "AI_GATEWAY"
type = "mcp"
integration_name = "@deco/ai-gateway"

[[deco.bindings]]
name = "DATABASE"
type = "mcp"
integration_name = "@deco/database"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_WORKFLOW_DO"
class_name = "Workflow"